apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=True
  destination:
    namespace: chatbot
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: git@github.com:erikhalt/pyttmanBOT.git
    targetRevision: master
    helm:
        values: | 
          enviroment: dev
          appname: chatbot
          deploymentname: chatbot-deployment
          image: erikhalt/chatbot:latest
          replicas: 1
          envar:
            DEBUG: 'False'
            DISCORD_TOKEN: 'MTE1NDc4OTI3NDYxMzQ1NjkxNg.GuoAX9.61Q549hBFkkIg647yZSE0lmwqGTBmZhIA6ZTrk'
            DISCORD_GUILD: 'https://discord.gg/74FRjcFZC'
